export {pallet as pallet_balances} from './balances'
export {default as pallet_system} from './system'
export {pallet as pallet_indecies} from './indecies'
export {default as pallet_identity} from './identity'
export {pallet as pallet_staking} from './staking'
export {pallet as pallet_session} from './session'
