manifestVersion: subsquid.io/v0.1
name: gs-main-amplitude
version: 1
description: |-
  Giant Squid Main for Amplitude chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: amplitude
    cmd: ["node", "lib/processor"]
  api:
    cmd:
      [
        "npx",
        "squid-graphql-server",
        "--dumb-cache",
        "in-memory",
        "--dumb-cache-ttl",
        "1000",
        "--dumb-cache-size",
        "100",
        "--dumb-cache-max-age",
        "1000",
      ]
